#!/usr/bin/env python3
"""Generate README.md for the repo from articles.json.

This creates a well-structured README with article links organized by category.
GitHub renders this at the repo root, providing DA 95+ backlinks.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EN_JSON = ROOT / 'en' / 'articles.json'
README = ROOT / 'README.md'
BASE = 'https://dingjiu1989-hue.github.io'


def generate_readme():
    data = json.loads(EN_JSON.read_text(encoding='utf-8'))
    site = data['site']
    boards = data['boards']

    total = sum(len(b['posts']) for b in boards)
    lines = []

    # Header
    lines.append(f'# {site["name"]}')
    lines.append('')
    lines.append(f'> {site["tagline"]}')
    lines.append('')
    lines.append(
        f'**{total} bilingual technical articles** — English & Chinese — '
        f'covering AI, web development, DevOps, tools, and side hustles.'
    )
    lines.append('')
    lines.append(f'🌐 **Website:** [{BASE}]({BASE}/en/)')
    lines.append(f'🤖 **AI-friendly index:** [`/en/llms.txt`]({BASE}/en/llms.txt)')
    lines.append(f'📡 **RSS:** [`/en/feed.xml`]({BASE}/en/feed.xml)')
    lines.append(f'📰 **JSON Feed:** [`/en/feed.json`]({BASE}/en/feed.json)')
    lines.append('')

    # Stats
    lines.append('## 📊 Stats')
    lines.append('')
    lines.append(f'- **Total articles:** {total}')
    lines.append(f'- **Categories:** {len(boards)}')
    lines.append(f'- **AI crawler optimized:** Yes (llms.txt, structured data, sitemap)')
    lines.append('')

    # Article index by category (concise — full list lives on the live site)
    lines.append('## 📚 Content by Category')
    lines.append('')
    lines.append(f'| Category | Articles | Link |')
    lines.append(f'|----------|----------|------|')

    for board in boards:
        board_name = board.get('name', board['id'])
        icon = board.get('icon', '📄')
        count = len(board['posts'])
        url = f'{BASE}/en/{board["id"]}/'
        lines.append(f'| {icon} {board_name} | {count} | [Browse]({url}) |')

    lines.append('')

    # Cross-platform
    lines.append('## 🔗 Cross-Platform')
    lines.append('')
    lines.append(f'- [Dev.to](https://dev.to/dingjiu1989) — {_count_sameas("dev.to")} articles with canonical URLs')
    lines.append(f'- [Hashnode](https://aisourcehub.hashnode.dev) — syndicated articles')
    lines.append('')

    # Footer
    lines.append('---')
    lines.append('')
    lines.append(
        '_Auto-generated by [`scripts/gen_readme.py`](scripts/gen_readme.py). '
        'Updated daily via GitHub Actions._'
    )
    lines.append('')

    readme = '\n'.join(lines)
    README.write_text(readme, encoding='utf-8')
    print(f'README.md written ({len(lines)} lines, {total} articles)')


def _count_sameas(domain):
    """Count sameAs entries for a domain."""
    path = ROOT / 'data' / 'sameas-urls.json'
    if path.exists():
        data = json.loads(path.read_text(encoding='utf-8'))
        count = sum(1 for v in data.values() if any(domain in u for u in v))
        return count
    return 0


if __name__ == '__main__':
    generate_readme()
